version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/js'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `root` directory
    directory: '/js'
    # Check for updates once a week
    schedule:
      interval: 'monthly'

  # Enable version updates for npm
  - package-ecosystem: 'pip'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/python'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `root` directory
    directory: '/python'
    # Check for updates once a week
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `root` directory
    directory: '/golang'
    # Check for updates once a week
    schedule:
      interval: 'monthly'
  # Enable version updates for npm
  - package-ecosystem: 'gomod'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/golang'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
