apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{- .Values.node.appName -}}-virtual"
spec:
  hosts: [{{- .Values.node.serviceName -}}] # адреса на яку звертається клієнт
  http:
    - route:
        - destination:
            host: "{{- .Values.node.serviceName -}}" # адреса на яку перенаправляється клієнт
      timeout: 5s
      retries:
        attempts: 3
        retryOn: 5xx
        perTryTimeout: 5s
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: "{{- .Values.node.appName -}}-destination"
spec:
  host: "{{- .Values.node.appName -}}-virtual"
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5 
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 80