apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{- .Values.persistanceVolume.name -}}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{- .Values.persistanceVolume.storage -}}"
